FROM --platform=linux/amd64 ubuntu:20.04
WORKDIR /app
#command to not have interactive mode to solve java install
ARG DEBIAN_FRONTEND=noninteractive
# Install base utilities
RUN apt-get update \
    && apt-get install -y build-essential \
    && apt-get install -y wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Define BLAST version
ENV BLAST_VERSION 2.14.0
# Download and install BLAST
RUN wget https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/${BLAST_VERSION}/ncbi-blast-${BLAST_VERSION}+-x64-linux.tar.gz \
    && tar -xzvf ncbi-blast-${BLAST_VERSION}+-x64-linux.tar.gz \
    && cp ncbi-blast-${BLAST_VERSION}+/bin/* /opt \
    && rm -r ncbi-blast-${BLAST_VERSION}+-x64-linux.tar.gz ncbi-blast-${BLAST_VERSION}+
ENV PATH=/opt:$PATH
